Repository netlify/plugins, pull requests merged in 2020-10, with the labels that each got.

#158 feat: update sitemap plugin
  plugins.json
Labels: type: feature

#161 Fix whitespaces linting
  .github/workflows/fossa.yml
  .gitignore
  LICENSE
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/request_deactivation.md
  docs/guidelines.md
  netlify.toml
  site/index.html
Labels: type: chore

#160 Use npm lock file instead of Yarn
  .gitignore
  package-lock.json
  yarn.lock
Labels: type: chore

#162 fix: update algoliasearch-netlify to v0.0.14
  plugins.json
Labels: type: bug

#164 Add documentation about releasing
  docs/CONTRIBUTING.md
Labels: type: chore

#165 chore: bump image-optim version
  plugins.json
Labels: type: feature
