Repository netlify/plugins, pull requests merged in 2020-07, with the labels that each got.

#108 docs(pr-template): remove manual npm diff instruction
  docs/PULL_REQUEST_TEMPLATE.md
Labels: type: chore

#106 feat: update lighthouse plugin
  plugins.json
Labels: type: feature

#114 feat: update lighthouse plugin
  plugins.json
Labels: type: feature

#119 feat: update netlify-purge-cloudflare-on-deploy
  plugins.json
Labels: feat/build-plugins, type: feature

#117 Upgrade version of @sentry/netlify-build-plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#122 feat(plugin-lighthouse): update to version 1.4.0
  plugins.json
Labels: type: feature

#102 Revert Algolia breaking changes
  plugins.json
Labels: type: bug
