Repository netlify/plugins, pull requests merged in 2020-03, with the labels that each got.

#8 Remove README hashes
  plugins.json
Labels: type: feature

#9 Add netlify-plugin-cypress
  plugins.json
Labels: type: feature

#10 add netlify-plugin-a11y
  plugins.json
Labels: documentation, type: feature

#11 rerun docs for Readme
  README.md
Labels: documentation, type: feature

#13 Temporarily hide Gatsby plugin from the UI.
  README.md
  plugins.json
Labels: type: bug
