Repository netlify/plugins, pull requests merged in 2020-06, with the labels that each got.

#75 ci: add npm-diff GitHub action
  .eslintrc.js
  .github/workflows/npmDiff.yml
  .gitignore
  .prettierrc
  commitlint.config.js
  package.json
  scripts/npm-diff.js
  yarn.lock
Labels: type: chore

#76 chore: reintroduce fossa
  .github/workflows/fossa.yml
Labels: type: chore

#79 Add Hugo cache resources to netlify plugins
  plugins.json
Labels: type: feature

#81 Fix link in PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: type: bug

#80 Add plugin netlify-purge-cloudflare-on-deploy
  plugins.json
Labels: type: feature

#82 Add netlify-plugin-submit-sitemap
  plugins.json
Labels: type: feature

#84 Version bump on Cloudflare cache purge
  plugins.json
Labels: type: bug

#85 Update plugins.json
  plugins.json
Labels: type: bug

#88 feat: add lighthouse plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#87 add netlify-plugin-inline-functions-env
  plugins.json
Labels: feat/build-plugins, type: feature

#91 ci(npm-diff): use custom token with write permissions
  .github/workflows/npmDiff.yml
  scripts/npm-diff.js
Labels: type: chore

#92 feat: update lighthouse plugin
  plugins.json
Labels: type: feature

#93 Bump and activate netlify-plugin-chromium
  plugins.json
Labels: type: bug

#90 Add netlify-plugin-html-validate
  plugins.json
Labels: feat/build-plugins, type: feature

#95 Bump netlify-plugin-inline-critical-css to 1.1.3
  plugins.json
Labels: type: bug

#96 feat: update lighthouse plugin
  plugins.json
Labels: type: feature

#97 refactor: use Netlify function for npm-diff instead of GitHub action
  .github/workflows/test.yml
  .gitignore
  functions/npm-diff.js
  functions/utils/validate.js
  netlify.toml
  package.json
  scripts/npm-diff.js
  site/index.html
  yarn.lock
Labels: type: chore

#99 Fix type in PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: type: bug

#101 fix: author for netlify-plugin-html-validate
  plugins.json
Labels: type: bug

#100 updates plugins.json to add gridsome cache plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#98 v1 released - Export directly to Algolia from postBuild
  plugins.json
Labels: feat/build-plugins, type: feature

#94 Install plugins in Dockerfile
  Dockerfile
  Jenkinsfile
  scripts/docker-build.sh
Labels: type: chore
