Repository netlify/plugins, pull requests merged in 2020-09, with the labels that each got.

#136 fix: update netlify-plugin-is-website-vulnerable
  plugins.json
Labels: type: bug

#153 fix: upgrade netlify-plugin-html-minify
  plugins.json
Labels: epic/bp2/on-success, type: feature

#154 Update plugin version
  plugins.json
Labels: type: chore
