Repository netlify/plugins, pull requests merged in 2020-12, with the labels that each got.

#181 Fix CORS with plugins.json
  netlify.toml
Labels: type: feature

#183 Fix Node.js version support
  package.json
Labels: type: bug

#179 Remove root `plugins.json`
  plugins.json
Labels: blocked, type: feature

#184 Ensure `plugins.json` is always valid
  .github/workflows/test.yml
  package-lock.json
  package.json
  test/main.js
Labels: type: chore

#186 fix: update sitemap plugin
  site/plugins.json
Labels: type: bug

#188 Remove Docker image
  Dockerfile
  Jenkinsfile
  scripts/docker-build.sh
Labels: type: feature

#189 Improve releasing documentation
  docs/CONTRIBUTING.md
Labels: type: chore
