Repository netlify/plugins, pull requests merged in 2020-05, with the labels that each got.

#24 added netlify-plugin-chromium
  README.md
  plugins.json
Labels: type: feature

#25 Add Inline Source plugin
  README.md
  plugins.json
Labels: type: feature

#27 Lock initial versions.
  plugins.json
Labels: type: feature

#40 Bump inline critical CSS plugin version
  plugins.json
Labels: type: chore

#41 Fix plugins.json file url typo in README.md
  README.md
Labels: documentation, type: bug

#42 Add netlify-plugin-pushover
  plugins.json
Labels: feat/build-plugins, type: feature

#45 Temporarily disable some plugins
  plugins.json
Labels: type: chore

#46 Upgrade plugins versions
  plugins.json
Labels: type: chore

#49 Update `@netlify/plugin-sitemap` version
  plugins.json
Labels: type: bug

#51 Upgrade version of Gatsby cache plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#50 Upgrade the version of `netlify-plugin-rss`
  plugins.json
Labels: type: chore

#44 Docs: Updates for contributors
  LICENSE
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE/request_deactivation.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/guidelines.md
  package.json
  scripts/docs.js
Labels: type: feature

#52 Upgrade version of @sentry/netlify-build-plugin
  plugins.json
Labels: type: chore

#53 Upgrade version of `netlify-plugin-a11y`
  plugins.json
Labels: type: chore

#54 feat: add netlify-plugin-is-website-vulnerable
  plugins.json
Labels: type: feature

#55 chore: fix pr template link
  docs/PULL_REQUEST_TEMPLATE.md
Labels: type: chore

#58 Deactivate plugins requiring inputs
  plugins.json
Labels: type: chore

#43 Add Algolia friendly Search Index plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#61 Bump inline-critical-css to 1.1.0
  plugins.json
Labels: type: chore

#60 Add AMP Server-Side Rendering plugin
  plugins.json
Labels: feat/build-plugins, type: feature

#62 Update AMP Server-Side Rendering plugin version
  plugins.json
Labels: type: bug

#23 Add image optim plugin
  plugins.json
Labels: type: feature

#63 bumping netlify-plugin-algolia-index version
  plugins.json
Labels: type: feature

#65 Update netlify-plugin-subfont to v5.0.3
  plugins.json
Labels: type: bug

#67 Bump netlify-plugin-inline-critical-css to 1.1.1
  plugins.json
Labels: type: bug

#68 Update netlify-plugin-cypress to 1.3.11
  plugins.json
Labels: type: chore

#70 Add npm diff to PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: type: chore

#66 Revert "create github actions workflow files for fossa"
  .github/workflows/fossa.yml
Labels: type: chore

#73 Upgrade version of @sentry/netlify-build-plugin
  plugins.json
Labels: type: bug

#74 Bump netlify-plugin-pushover version
  plugins.json
Labels: type: bug

#64 Adds Dareboost plugin
  plugins.json
Labels: type: feature
