Repository netlify/plugins, pull requests merged in 2021-04, with the labels that each got.

#267 feat: add QA Wolf plugin
  site/plugins.json
Labels: feat/build-plugins, type: feature

#276 chore: update QA Wolf plugin
  site/plugins.json
Labels: feat/build-plugins, type: chore

#281 feat: update version of @sentry/netlify-build-plugin
  site/plugins.json
Labels: type: feature

#290 feat: upgrade essential next.js to 3.2.0
  site/plugins.json
Labels: type: feature

#291 Revert "chore: upgrade essential next.js to 3.2.0"
  site/plugins.json
Labels: type: bug
