Repository netlify/plugins, pull requests merged in 2021-12, with the labels that each got.

#506 chore!: use pure ES modules
  .eslintrc.cjs
  commitlint.config.cjs
  functions/npm-diff/compute.js
  functions/npm-diff/fetch.js
  functions/npm-diff/index.js
  functions/npm-diff/new_urls.js
  functions/npm-diff/upsert_comment.js
  functions/npm-diff/validate.js
  index.js
  package.json
  test/main.js
Labels: type: chore

#509 fix: main file is missing
  package.json
Labels: type: bug, automerge

#530 feat: bump Inline Critical CSS to v2.0.0
  site/plugins.json
Labels: type: chore, type: feature

#531 feat: upgrade Next plugin to 4.0.0
  .gitignore
  site/plugins.json
Labels: automerge
