Repository netlify/plugins, pull requests merged in 2021-05, with the labels that each got.

#284 feat: add Ghost Inspector Netlify plugin
  site/plugins.json
Labels: type: feature

#294 upgrade essential next.js to 3.2.1
  site/plugins.json
Labels: type: feature

#296 chore: simplify test
  package.json
  test/main.mjs
Labels: type: chore

#299 feat: allow `compatibility` entries without conditions
  test/main.mjs
Labels: type: feature

#307 chore: bump v1 essential nextjs plugin to v1.1.4
  site/plugins.json
Labels: type: chore

#315 fix: Fix Camel case. Stepzen --> StepZen
  site/plugins.json
Labels: type: bug

#314 feat: upgrade `netlify-plugin-html-validate` to `1.0.0`
  site/plugins.json
Labels: type: feature

#306 feat: Add Airbrake Netlify plugin
  site/plugins.json
Labels: type: feature

#317 feat: add `migrationGuide` to `netlify-plugin-html-validate@v1`
  site/plugins.json
Labels: type: feature

#318 chore: fix HTML validate plugin migration URL
  site/plugins.json
Labels: type: feature

#320 feat: enforce that the first field in `compatibility` is the same as `version`
  site/plugins.json
  test/main.mjs
Labels: type: feature

#325 chore: update essential nextjs to 3.3.0
  site/plugins.json
Labels: type: chore

#323 feat: add Cecil cache
  site/plugins.json
Labels: type: feature

#322 Bump netlify-plugin-subfont version to v6
  site/plugins.json
Labels: type: feature

#324 feat: add documentation about breaking changes in plugins
  docs/CONTRIBUTING.md
  docs/plugin_review.md
Labels: documentation, type: feature

#237 feat: update Cypress E2E plugin
  site/plugins.json
Labels: type: feature

#329 chore: run CI on latest Node.js
  .github/workflows/release-please.yml
  .github/workflows/test.yml
Labels: type: chore

#333 fix: Update version netlify-plugin-stepzen
  site/plugins.json
Labels: type: feature

#337 chore: update essential nextjs to 3.3.1
  site/plugins.json
Labels: type: chore
