Repository netlify/plugins, pull requests merged in 2021-09, with the labels that each got.

#437 feat: update angular universal plugin to 1.0.1
  site/plugins.json
Labels: type: feature

#441 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#447 fix: corner case causing build internal error.
  site/plugins.json
Labels: type: bug

#452 fix: deactivate `netlify-plugin-search-index`
  site/plugins.json
Labels: type: bug

#454 chore: use same `.gitignore` as other projects
  .gitignore
Labels: type: chore

#457 chore: add `.editorconfig`
  .editorconfig
Labels: type: chore

#458 chore: add `.gitattributes`
  .gitattributes
Labels: type: chore

#455 chore: use `@netlify/eslint-config-node` setup
  .eslintrc.js
  .github/workflows/test.yml
  .prettierrc
  .prettierrc.json
  commitlint.config.js
  functions/npm-diff.js
  functions/utils/validate.js
  index.js
  package-lock.json
  package.json
  test/main.mjs
Labels: type: chore

#456 chore!: drop Node 8
  package-lock.json
  package.json
Labels: type: chore

#461 chore: refactor `getNewPluginsUrls()`
  functions/npm-diff.js
Labels: type: chore

#463 chore: refactor diff URLs printing
  functions/npm-diff.js
Labels: type: chore

#462 chore: refactor HTTP requests
  functions/npm-diff.js
Labels: type: chore

#465 chore: refactor main handling logic
  functions/npm-diff.js
Labels: type: chore

#466 chore: break into multiple files
  functions/npm-diff.js
  functions/npm-diff/compute.js
  functions/npm-diff/fetch.js
  functions/npm-diff/index.js
  functions/npm-diff/new_urls.js
  functions/npm-diff/upsert_comment.js
  functions/npm-diff/validate.js
Labels: type: chore

#467 chore: refactor plugins diff
  functions/npm-diff/compute.js
Labels: type: chore

#464 chore: refactor validation
  functions/npm-diff/index.js
  functions/npm-diff/validate.js
Labels: type: chore
