Repository netlify/plugins, pull requests merged in 2021-03, with the labels that each got.

#226 feat: allow and validate `compatibility` field
  package-lock.json
  package.json
  test/main.js
Labels: type: feature

#227 chore: upgrade Lighthouse plugin
  site/plugins.json
Labels: type: chore

#228 chore: upgrade Lighthouse plugin with `compatibility` field
  site/plugins.json
Labels: type: chore

#229 chore: add Renovate
  renovate.json5
Labels: type: chore

#230 chore: add `release-please`
  .github/workflows/release-please.yml
Labels: type: chore

#233 feat: support Next <10.0.6 users with Essential Next.js plugin
  site/plugins.json
Labels: type: feature

#225 Add webmentions plugin
  site/plugins.json
Labels: feat/build-plugins, type: feature

#235 chore: fix tests timeout
  package.json
Labels: type: chore

#239 fix: Essential Next.js 3.0.1
  site/plugins.json
Labels: type: bug

#242 fix: revert Essential Next.js 3.0.0
  site/plugins.json
Labels: type: bug

#241 fix: upgrade Essential Next.js `3.0.3`
  site/plugins.json
Labels: type: bug

#246 fix: upgrade Essential Next.js to `1.1.3`
  site/plugins.json
Labels: type: bug

#249 feat(sitemap): bump sitemap plugin to 0.8.0
  site/plugins.json
Labels: feat/build-plugins, type: feature
