Repository netlify/plugins, pull requests merged in 2021-06, with the labels that each got.

#339 chore: upgrade essential next.js to 3.4.0
  site/plugins.json
Labels: type: chore

#340 Revert "chore: upgrade essential next.js to 3.4.0"
  site/plugins.json
Labels: type: chore

#341 chore: upgrade essential next.js to 3.4.1
  site/plugins.json
Labels: type: chore

#342 Revert "chore: upgrade essential next.js to 3.4.1"
  site/plugins.json
Labels: type: chore

#344 chore: upgrade nextjs to 3.4.2
  site/plugins.json
Labels: type: chore

#345 feat: bump netlify-plugin-pushover to 0.1.1 for enhancements
  site/plugins.json
Labels: type: chore

#357 feat(qawolf): bump qawolf to 1.2.0
  site/plugins.json
Labels: feat/build-plugins

#359 feat: update netlify-plugin-visual-diff to 1.3.0 and 2.0.0
  site/plugins.json
Labels: type: bug

#356 feat(plugin-gatsby): add Essential Gatsby plugin
  site/plugins.json
Labels: blocked, feat/build-plugins, type: feature

#370 chore: upgrade essential next to 3.5.0
  site/plugins.json
Labels: type: chore
