Repository netlify/plugins, pull requests merged in 2021-08, with the labels that each got.

#402 chore: bump `plugins.json` to v2
  .github/workflows/versioning.yml
  docs/versioning.md
Labels: type: chore

#407 chore!: expose `pluginsUrl`
  docs/versioning.md
  index.js
  test/main.mjs
Labels: type: chore

#409 fix: main entry point
  package.json
Labels: type: bug

#411 feat: add `featureFlag` property
  test/main.mjs
Labels: type: feature

#418 feat: add essential angular universal beta
  site/plugins.json
Labels: type: feature

#423 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore, automerge

#433 feat: guidelines for proper `netlifyConfig` usage
  docs/plugin_review.md
Labels: type: feature

#432 chore: fix indentation
  docs/guidelines.md
Labels: type: chore

#436 chore(ci): cache npm cache dir between workflow execs
  .github/workflows/release-please.yml
  .github/workflows/test.yml
Labels: type: chore, automerge

#431 feat: update essential next to 3.9.0
  site/plugins.json
Labels: type: feature
