Repository netlify/plugins, pull requests merged in 2022-10, with the labels that each got.

#854 feat: update version of Cecil cache
  site/plugins.json
Labels: automerge

#839 chore(plugins): add snaplet plugin to public directory
  site/plugins.json
Labels: automerge

#868 feat: add netlify-plugin-formspree
  site/plugins.json
Labels: automerge

#870 chore: remove support for node 12
  package.json
Labels: type: chore, automerge

#888 chore: manually update CMS sync changes
  site/plugins.json
Labels: automerge

#873 fix: update netlify-plugin-formspree version
  site/plugins.json
Labels: automerge

#895 feat: add emails plugin
  site/plugins.json
Labels: automerge

#911 chore: update email plugin version
  site/plugins.json
Labels: automerge

#843 feat: add inngest plugin to directory
  site/plugins.json
Labels: automerge

#935 fix: revert plugin @netlify/plugin-nextjs to version 4.25.0
  site/plugins.json
Labels: automerge

#924 chore(main): switches marketplace naming to integrations
  .github/CODEOWNERS
Labels: type: chore

#925 chore: updates wording to match Sanity
  site/plugins.json
Labels: type: chore

#938 fix: update Next plugin to 4.27.1
  site/plugins.json
Labels: automerge

#943 fix: roll back Next to 4.26.0
  site/plugins.json
Labels: automerge

#946 feat: support env vars in plugin definitions
  bin/utils.js
  test/bin/utils.js
Labels: automerge

#947 fix: update Next plugin to 4.27.2
  site/plugins.json
Labels: automerge

#954 fix: use generated token for sanity to github plugin sync
  .github/workflows/sync-cms-to-repo.yml
Labels: automerge

#955 fix: add token-generator-bot to git signature
  .github/workflows/sync-cms-to-repo.yml
Labels: automerge

#957 fix: add variables to build step test
  test/main.js
Labels: automerge

#966 feat: add feature-flagged version of Next runtime
  site/plugins.json
Labels: automerge

#995 fix: add packageName to variable tests
  test/main.js
Labels: automerge
