Repository netlify/plugins, pull requests merged in 2022-05, with the labels that each got.

#724 feat: update plugin @netlify/plugin-nextjs to version 4.7.0
  site/plugins.json
Labels: feat/build-plugins, automerge

#726 feat: add Very Good Security plugin
  site/plugins.json
Labels: automerge

#730 feat: add TakeShape plugin
  site/plugins.json
Labels: automerge

#740 fix: rollback to earlier version of Gatsby plugin
  site/plugins.json
Labels: type: bug
