Repository netlify/plugins, pull requests merged in 2022-01, with the labels that each got.

#608 chore(deps): switch to c8, remove unneeded devDependencies
  .gitignore
  package-lock.json
  package.json
Labels: type: chore, automerge

#614 chore: fix Husky
  package.json
Labels: type: chore, automerge

#615 fix: husky binary not found
  package-lock.json
  package.json
Labels: type: bug, automerge

#622 fix: bump `netlify-plugin-debug-cache` to `1.0.4`
  site/plugins.json
Labels: type: bug

#627 fix: update to Next 4.2.1
  site/plugins.json
Labels: automerge

#629 feat: update plugin netlify-plugin-is-website-vulnerable to version 2.0.1
  site/plugins.json
Labels: automerge
