Repository netlify/plugins, pull requests merged in 2022-02, with the labels that each got.

#635 feat: upgrade skip nx plugin to 0.0.5
  site/plugins.json
Labels: type: feature

#648 chore: use ESM-specific ESLint configuration
  renovate.json5
Labels: type: chore, automerge

#643 chore: use ESM-specific ESLint configuration
  .eslintrc.cjs
Labels: type: chore

#631 feat: plugin Submission: CommandBar + Netlify
  site/plugins.json
Labels: type: feature

#657 fix: upgrade netlify-plugin-commandbar version to `0.0.4`
  site/plugins.json
Labels: type: bug

#659 fix(plugins): update Algolia crawler
  site/plugins.json
Labels: type: bug

#661 Revert Algolia crawler latest update
  site/plugins.json
Labels: type: bug

#664 feat: update plugin @netlify/plugin-nextjs to version 4.2.7
  site/plugins.json
Labels: type: chore, automerge

#626 feat: upgrade Lighthouse plugin to `2.1.3`
  site/plugins.json
Labels: type: feature, automerge

#669 fix: update Gatsby plugin to 2.0.3
  site/plugins.json
Labels: type: bug, automerge

#671 feat: update version of @sentry/netlify-build-plugin
  site/plugins.json
Labels: type: feature

#673 Add Cloudinary plugin
  site/plugins.json
Labels: automerge
