Repository netlify/plugins, pull requests merged in 2022-09, with the labels that each got.

#821 feat: upgrade next runtime version
  site/plugins.json
Labels: type: feature, automerge

#827 feat: testing display preferences for plugins
  .gitignore
  site/plugins.json
Labels: automerge

#826 feat: add `netlify-plugin-playwright-cache`
  site/plugins.json
Labels: automerge

#811 feat: update `netlify-plugin-ghost-markdown` to v3.1.0
  site/plugins.json
Labels: type: feature, automerge

#852 chore: update codeowners
  .github/CODEOWNERS
Labels: type: chore
