Repository netlify/plugins, pull requests merged in 2022-03, with the labels that each got.

#677 feat: update plugin netlify-plugin-is-website-vulnerable to version 2.0.3
  site/plugins.json
Labels: type: feature

#679 feat: update Gatsby to 2.1.1
  site/plugins.json
Labels: automerge

#681 fix: update Gatsby to 2.1.2
  site/plugins.json
Labels: automerge

#685 fix: upgrade netlify-plugin-stepzen version to 1.0.4
  site/plugins.json
Labels: type: bug

#695 chore: updating netlify-plugin-cloudinary to 1.0.3
  site/plugins.json
Labels: type: chore

#700 fix: update Next plugin to 4.3.1
  site/plugins.json
Labels: automerge
